    <nav class="main-nav">
	<div>
	    <ul>
                <li class="menu-item">
                    <a href="sumeru.html"><b>Sumeru</b></a>
                </li>
                <li class="menu-item">
                    <a href=""><b>Sake</b></a>
                </li>
                <li class="menu-item">
                    <a href=""><b>Forum</b></a>
		</li>
                <li class="menu-item">
                    <a href=""><b>Store</b></a>
                </li>
                <li class="menu-item">
                    <a href="contact.html"><b>Contact</b></a>
                </li>
            </ul>
        </div>
    </nav>
