    <nav class="main-nav">
	<div>
	    <ul>
                <li class="menu-item">
                    <a href="sumeru.html">Sumeru</a>
                </li>
                <li class="menu-item">
                    <a href="">Sake</a>
                </li>
                <li class="menu-item">
                    <a href="">Forum</a>
		</li>
                <li class="menu-item">
                    <a href="">Store</a>
                </li>
                <li class="menu-item">
                    <a href="contact.html">Contact</a>
                </li>
            </ul>
        </div>
    </nav>
