<ul>
    <li><a href="mailto:support@purpe.com">Email: support@purpe.com</a></li>
    <li><a href="sumeru-troubleshooting.html">Board Troubleshooting<a></li>
    <li><a href="https://groups.google.com/g/purpose-research-sumeru">Developer mailing list</a></li>
    <li><a href="https://groups.google.com/g/purpose-research-sake">CPU mailing list</a></li>
    <li><a href="https://groups.google.com/g/purpose-research-support">Product Errata mailing list</a></li>
</ul>
