<ul>
    <li><a href="sumeru-get-started.html" target="_blank">Get started with your new board ...</a></li>
    <li><a href="sumeru-dev-guide.html" target="_blank">SUMERU SBC - Developer Guide</a></li>
    <li><a href="sake-dev-guide.html" target="_blank">SAKE CPU - Developer Guide<a></li>
    <li><a href="images/sumeru-v1_0-schematic-color.pdf">Sumeru v1.0 Board Schematics<a></li>
    <li><a href="images/sumeru-v1_0-pinout.png" target="_blank">Sumeru v1.0 Pin-out diagram<a></li>
</ul>
