include ${SUMERU_DIR}/conf/mk/sumeru-pre.mk

LIB = libsumeru_unistd.a

CFILES = $(wildcard *.c)

CFLAGS += -Werror -Wno-stringop-truncation
CFLAGS += -I../fs_yaffs2

include ${SUMERU_DIR}/conf/mk/sumeru-lib-post.mk
