include ${SUMERU_DIR}/conf/mk/sumeru-pre.mk

LIB = libsumeru_fs_yaffs2.a

CFILES = $(wildcard *.c)
ASMFILES = $(wildcard *.S)

#CFLAGS += -DGLUE_ENABLE_PRINTF
#CFLAGS += -DENABLE_YAFFS_TRACE

CFLAGS += -Werror

include ${SUMERU_DIR}/conf/mk/sumeru-lib-post.mk
